### ISSUE TITLE
Getting Exception when running against 5.10.1

### ISSUE THREAD

**Issue by nellb28** [kazurayam/UsingApplitoolsWithinKatalonStudio#2]
I am getting the following error when trying to run your sample script. I am using Katalon v5.10.1.

Reason:
BUG! exception in phase 'semantic analysis' in source unit 'file:/C:/Users/nbrisard/Downloads/UsingApplitoolsWithinKatalonStudio-master/Scripts/test01/Script1523260020936.groovy' ClassNode#getTypeClass for Script1523260020936 is called before the type class is set 
	at com.kms.katalon.core.ast.AstTextValueUtil.getTextValue(AstTextValueUtil.java:252)
	at com.kms.katalon.core.ast.AstTextValueUtil.getTextValue(AstTextValueUtil.java:181)
	at com.kms.katalon.core.ast.AstTextValueUtil.getTextValue(AstTextValueUtil.java:248)
	at com.kms.katalon.core.ast.AstTextValueUtil.getTextValue(AstTextValueUtil.java:177)
	at com.kms.katalon.core.ast.AstTextValueUtil.getTextValue(AstTextValueUtil.java:101)
	at com.kms.katalon.core.ast.AstTextValueUtil.getTextValue(AstTextValueUtil.java:71)
	at com.kms.katalon.core.ast.AstTestStepTransformation.getKeywordNameForStatement(AstTestStepTransformation.groovy:314)
	at com.kms.katalon.core.ast.AstTestStepTransformation.visit(AstTestStepTransformation.groovy:262)
	at com.kms.katalon.core.ast.AstTestStepTransformation.visit(AstTestStepTransformation.groovy:86)
	at com.kms.katalon.core.main.ScriptEngine.getScript(ScriptEngine.java:199)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:106)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:97)
	at com.kms.katalon.core.main.TestCaseMain$runTestCase$0.call(Unknown Source)
	at TempTestCase1550345056357.run(TempTestCase1550345056357.groovy:22)

**Comment by kazurayam** [comment]
>BUG! exception in phase 'semantic analysis' in source unit

Please refer to the following discussion:

https://forum.katalon.com/t/reason-bug-exception-in-phase-semantic-analysis-in-source-unit/15451

Perhaps, the following 2 lines are problematic:
```
static private Eyes createEyes() {
```

```
static private void handleResult(TestResults result) {
```

Please remove `static`, and try

**Comment by nellb28** [comment]
Sorry for the late reply, but that fixed it
